version: '3.8'

services:
  db:
    image: postgres:14  # Use the version of PostgreSQL you prefer
    container_name: pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge
